name: Enjoy Experiences
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef3f6'
    - '#080c0c'
    - '#b50000'
    - '#444b4c'
    - '#cb8425'
  brandStrength: 0.5611094606574625
  lightness: 0.10316377645358443
  saturation: 0.005702166352421045
  rhythmicContrast: 0.030065295984968543
purpose: []
